!
!***************************************************************************
!*************************END OF GAS DATABASE*******************************
!***************************************************************************
!
SUBROUTINE ALLOCATE_GAS
!
USE GAS
USE CALC
USE MOLECS
USE MFDSMC,only : IMF, IMFS, NMFANG, IMFpair, MFRMASS, NMFER0, NMFET0,NMFEV0,NMFER,&
  NMFET,NMFEV,NMFERR,NMFETR,NMFEVR,NMFVT0,NMFVT,NMFVTR
USE EXPCOL,only : EXPCOL_INIT
!
IMPLICIT NONE
INTEGER :: NMFpair0
!
ALLOCATE (FSP(MSP,2),SP(5,MSP),SPR(3,MSP),SPM(8,MSP,MSP),ISPR(2,MSP),ISPV(MSP),ENTR(6,MSP,2),NRSP(MSP,MSP),      &
          VMP(MSP,2),UVMP(MSP,2),VNMAX(MSP),CR(MSP),TCOL(MSP,MSP),CSCR(MSP,MSP),ISPRC(MSP,MSP),SPRC(2,MSP,MSP,MSP),STAT=ERROR)  !--isebasti: UVMP included
!
IF (ERROR /= 0) THEN
  WRITE (*,*)'PROGRAM COULD NOT ALLOCATE SPECIES VARIABLES',ERROR
END IF
!
ALLOCATE (NEX(MMEX,MSP,MSP),NSPEX(MSP,MSP),SPEX(3,MMEX,MSP,MSP),ISPEX(MMEX,0:4,MSP,MSP),TREACG(4,MSP),         &
          PSF(MMEX),TREACL(4,MSP),TNEX(MEX),STAT=ERROR)
!
IF (ERROR /= 0) THEN
  WRITE (*,*)'PROGRAM COULD NOT ALLOCATE Q-K REACTION VARIABLES',ERROR
END IF
!
IF (MMVM > 0) THEN  !--isebasti: IDL,CPER,DPER,IREV included
  ALLOCATE (SPVM(4,MMVM,MSP),ISPVM(2,MMVM,MSP),IDL(MMVM,MSP),DPER(MSP),IVMODEL(MSP,2),VIBEN(0:100,MSP),STAT=ERROR)
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE VIBRATION VARIABLES',ERROR
  END IF
  IVMODEL(:,1)=0   !initializing variable
  IVMODEL(:,2)=100 !initializing variable; must be the same number in the vibrational pdf sampling variables
END IF
!
IF (MNRE > 0) THEN
  ALLOCATE (CI(MNRE),AE(MNRE),AC(MNRE),BC(MNRE),ER(MNRE),REA(6,MNRE),LE(MNRE),ME(MNRE),KP(MNRE),LP(MNRE),MP(MNRE),      &
            IREA(2,MNRE),JREA(2,MNRE,2),IRCD(MNRE,MSP,MSP),NREA(2,MNRE),CPER(MNRE,2),IREV(MNRE),STAT=ERROR)
  ALLOCATE (NPVIB(2,MNRE,3,3,0:100),FPVIB(MNRE,ITMAX,3,3,0:100),FPTEMP(ITMAX),STAT=ERROR) !--isebasti: included
  ALLOCATE (NEVIB(MNRE,2,0:100),FEVIB(MNRE,ITMAX,2,0:100),STAT=ERROR) !--isebasti: included
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE REACTION VARIABLES A',ERROR
  END IF
ELSE
  ALLOCATE (NPVIB(1,1,1,1,1),FPVIB(1,1,1,1,1),FPTEMP(1),NEVIB(1,1,1),FEVIB(1,1,1,1),STAT=ERROR) !--isebasti: included
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE REACTION VARIABLES B',ERROR
  END IF
END IF
!
IF (MTBP > 0) THEN
  ALLOCATE (THBP(MTBP,MSP),STAT=ERROR)
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE THIRD BODY VARIABLES',ERROR
  END IF
END IF
!
IF (MNSR > 0) THEN
  ALLOCATE (ERS(MNSR),LIS(2,MNSR),LRS(6,MNSR),ISRCD(MNSR,MSP),STAT=ERROR)
  IF (ERROR /= 0) THEN
    WRITE (*,*)'PROGRAM COULD NOT ALLOCATE SURFACE REACTION VARIABLES',ERROR
  END IF
END IF
!
!-- Allocate variables related to MF model
IF (MNRE > 0 .AND. IMF .ne. 0) THEN
  ALLOCATE(NMFANG(MNRE),MFRMASS(3,MNRE),STAT = ERROR)
  !--count number of pairs
  NMFpair0 = FLOOR(DBLE(MSP*(MSP+1))/2.0d0)
  IF (IMFS == 1 ) THEN
    ALLOCATE(IMFpair(MSP,MSP),NMFER0(1000,2,NMFpair0), NMFET0(1000,NMFpair0),NMFEV0(0:100,2,NMFpair0), &
      NMFER(1000,2,NMFpair0), NMFET(1000,NMFpair0),NMFEV(0:100,2,NMFpair0), &
      NMFERR(1000,2,MNRE),   NMFETR(1000,MNRE),  NMFEVR(0:100,2,MNRE), &
      NMFVT0(0:100,1000,2,NMFpair0), NMFVT(0:100,1000,2,NMFpair0),NMFVTR(0:100,1000,2,MNRE),STAT=ERROR)
    IF (ERROR /= 0) THEN
      WRITE(*,*) 'PROGRAM COULD NOT ALLOCATE SPACE FOR MF RELATED VARIBALES', ERROR
      STOP
    ENDIF
  ELSE
  ! allocate dummy variable due to the reduction in SUBROUTINE COLLISION
  !$  ALLOCATE(NMFET0(1,1), NMFER0(1,2,1), NMFEV0(1,2,1), NMFVT0(1,1,2,1), &
  !$            NMFEV(1,2,1), NMFET(1,1), NMFER(1,2,1), NMFVT(1,1,2,1), STAT=ERROR)
  !$  IF (ERROR /= 0) THEN
  !$    WRITE(*,*) 'PROGRAM COULD NOT ALLOCATE SPACE FOR OPENMP DUMMY VARIABLE', ERROR
  !$    STOP
  !$  END IF
  END IF
ELSE
! allocate dummy variable due to the reduction in SUBROUTINE COLLISION
!$  ALLOCATE(NMFET0(1,1), NMFER0(1,2,1), NMFEV0(1,2,1), NMFVT0(1,1,2,1), &
!$            NMFEV(1,2,1), NMFET(1,1), NMFER(1,2,1), NMFVT(1,1,2,1), STAT=ERROR)
!$  IF (ERROR /= 0) THEN
!$    WRITE(*,*) 'PROGRAM COULD NOT ALLOCATE SPACE FOR OPENMP DUMMY VARIABLE', ERROR
!$    STOP
!$  END IF
END IF


!-- Allocate variables related to nonVHS model
ALLOCATE(INONVHS(MSP,MSP), STAT=ERROR)
IF (ERROR /= 0) THEN
  WRITE(*,*) 'PROGRAM COULD NOT ALLOCATE SPACE FOR nonVHS RELATED VARIBALES', ERROR
  STOP
ENDIF
INONVHS = 0
IF (GASCODE .eq. 8) THEN
  IF (nonVHS == 2) THEN
    CALL EXPCOL_INIT()
  ELSE IF (nonVHS == 1) THEN
    INONVHS(1,4) = 1
    INONVHS(4,1) = 1
  ELSE IF (nonVHS == 3) THEN
    INONVHS = 0
  END IF
END IF

RETURN
END SUBROUTINE ALLOCATE_GAS
